Code Review Request
mahdimahdawi/To-Do-list-codeRview pull request #1
Opened 2022-08-23 08:06 UTC by mahdimahdawi

**This PR contain:**
- whole To Do List project 
- please kindly review this PR.

2022-08-23 09:47 UTC, megha-n-bodke commented
Please correct linter errors.

2022-08-23 13:17 UTC, shella12 commented on src/list.js
> +/* eslint-disable */
I would suggest not disabling the linters and fixing the problem manually because linters are there to ensure best practices.

2022-08-23 13:20 UTC, shella12 commented on src/list.js
> +import 'lodash';
It's better to remove any imports or codes that are not being used, in accordance with the YAGNI principle.

2022-08-23 13:26 UTC, shella12 commented on src/list.js
> +  const removeBtn = document.createElement('img');
I would suggest declaring all the variables once at the start of the function to make the code look cleaner.

2022-08-23 13:34 UTC, shella12 requested changes
I see some linter errors showing in your project, I would suggest you look at them and fix them to ensure the use of best practices

2022-08-23 13:37 UTC, shella12 requested changes
#  *Status: Invalidated* :red_circle: 

Hi @soesandarwin2201 , 

While you made a great effort in this project, unfortunately, according to Microverse rules I cannot proceed to review your code. 

## Invalid Code Review Request

You have submitted a project, that 

- [x] has linter errors.

Please address the linter errors and resubmit your request for review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-08-24 05:49 UTC, mahdimahdawi commented
Thank You @shella12 for reviewing PR.
I will fix all issues that your mentioned here.
Thank You  🤞😊

2022-08-24 05:50 UTC, merged

2022-12-23 06:51 UTC, shella12 reviewed
Hi @mahdimahdawi ,

:thumbsup: Thumbs up for making it this far, your project is really nice, and congratulations on the good work you have done so far.

There are a few things you need to address to make your code more refined but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Good implementation of requirements

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.


# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

_Check the comments under the review._ 

***

Cheers and Happy coding! :clap: :clap: :clap:

2022-12-23 06:51 UTC, shella12 commented on src/index.js
> +import 'lodash';
- [ ] I suggest removing any imports or codes that are not being used, in accordance with the YAGNI principle. Removing dead code that eats up runtime and memory is the easiest way to improve performance because it can be deleted and the application's functionality won't be impacted.

2022-12-23 06:51 UTC, shella12 commented on src/list.js
> +  const removeBtn = document.createElement('img');
- [ ] I would suggest declaring all the variables once at the start of the function to make the code look cleaner.

2022-12-23 06:51 UTC, shella12 commented on src/list.js
> +/* eslint-disable */
- [ ] I would suggest not disabling the linters and fixing the problem manually because linters are there to ensure best practices.

2022-12-23 06:51 UTC, shella12 commented on src/list.js
> +};
- [ ] Writing the function in a way that each function performs one task and only one task alone makes your code much more manageable and dependency-free. I suggest you make the functions exclusive to their tasks e.g. if you write the `UpdateTask` function it should only include code relevant to updating the item. Displaying the items should be done in a separate function.

2022-12-23 06:51 UTC, shella12 commented on src/list.js
> +      order.appendChild(checkbox);
- [ ] [OPTIONAL] I suggest using template literals where ever possible. Template literals enable you to span two or more lines with a single string resulting in clean code